name: Atualizar Pac-Man Contribution

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite
  workflow_dispatch:     # Permite execução manual

jobs:
  build:
    permissions:
      contents: write  # Permite que a Action faça commits

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Gráfico de Contribuição Pac-Man
        uses: AndreRuperto/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.PAT_TOKEN }}
          theme: github-dark

      - name: Instalar dependências para conversão
        run: |
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin imagemagick

      - name: Converter SVG animado em GIF
        run: |
          mkdir -p dist
          convert -density 300 dist/pacman-contribution-graph-dark.svg -layers Optimize dist/pacman.gif

      - name: Publicar SVG e GIF na branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
